### PR TITLE
Add serialization test and fix NumUniqueSeparators

### LINKED ISSUE #113: NumUniqueSeparators error when serialized to JSON
Separators is a set which causes error when getting serialized to JSON

### PR DESCRIPTION
**Pull request by thehomebrewnerd**
Moves serialization test from `TestLSA` to `PrimitiveT` so all primitives are tested for ability to serialize.

Fixes serialization issue with `NumUniqueSeparators`

Closes #113

### CODE REVIEW

**Comment by rwedge** [comment]
I think the calculate feature matrix calls are extending the total time spent for the unit tests by a lot

Do you think that confirming saving and loading the feature would be sufficient for the test (and skip calculating the feature matrixes)?

**Comment by thehomebrewnerd** [comment]
> Do you think that confirming saving and loading the feature would be sufficient for the test (and skip calculating the feature matrixes)?

I think most of the increased time comes from the Elmo serialization test (at least when I test locally). Testing with CFM might be a little overkill, but if we skip CFM with Elmo I think things will run much faster. Let me test it out.

**Comment by thehomebrewnerd** [comment]
@rwedge Things seem much faster after this change: [e27ee38](https://github.com/alteryx/nlp_primitives/pull/122/commits/e27ee38318bb16d6aec2fd624d640cb9929b800e)

Should we go with something like this or just drop the CFM stuff completely?

**Comment by rwedge** [comment]
@thehomebrewnerd  Let's keep CFM (barring ELMO)

I'd like to make a call to  the serialized feature's primitive `get_function` before serialization, since for `LSA` that's when the  sklearn pipeline is initialized

**Review by dvreed77 — APPROVED** [review]
lgtm

**Pull request merged**
