### PR TITLE
Add TokenCount primitive

### PR DESCRIPTION
**Pull request by tuethan1999**
#73

### CODE REVIEW

**Comment by tuethan1999** [comment]
There's the potential for this primitive to create a LOT of output features since potentially every word can get tokenized

**Comment by thehomebrewnerd** [comment]
> There's the potential for this primitive to create a LOT of output features since potentially every word can get tokenized

I am a little concerned by this behavior. Is this what we really want? I tested this primitive on a dataset with restaurant reviews and this primitive created a single feature (`<Feature: TOKEN_COUNT(Review)>`) that added 1,969 columns to  the feature matrix.

image

**Comment by gsheni** [comment]
Let's discuss this primitive at standup.

**Comment by tuethan1999** [comment]
@alteryx/ml-tools decided that the large number of features this primitive produces isn't worth the functionality

**Pull request closed without merging**
